config/routes.rb
RailsBlog::Application.routes.draw do
  resources :authors

  resources :posts do
    resources :comments, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :comments

  root :to => 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :author
  belongs_to :post
  attr_accessible :content, :author_id, :post_id

  validates :content, :author_id, :post_id, :presence => true 

  include ActionView::Helpers::UrlHelper
  # include  ActionDispatch::Http::Url

  PREVIEW_LIMIT = 340
  LINE_LIMIT = 4

  def paragraphize
    content.split("\n").collect{|paragraph| "<p>#{paragraph}</p>"}.join("\n")
  end

  def preview
    if content.scan("\n").size > LINE_LIMIT
      paragraphize[0..PREVIEW_LIMIT].split("\n")[0..LINE_LIMIT].collect{|paragraph| "<p>#{paragraph}</p>"}.join("\n") + ellipsis
    elsif paragraphize.size > PREVIEW_LIMIT
      paragraphize[0..PREVIEW_LIMIT] + ellipsis
    else
      paragraphize
    end
  end

  def ellipsis
    "<strong>#{link_to '...', '/posts/'+self.post_id.to_s}<strong>"
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new(:post_id => params[:post_id])

    if request.referer.is_a? String
      resource_type = request.referer.split("/")[-2]
      resource_id   = request.referer.split("/")[-1]
      @selected_post    = resource_id.to_i  if resource_type = "posts"
      @selected_author  = resource_id.to_i  if resource_type = "authors"
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])

    @selected_post    = @comment.post_id
    @selected_author  = @comment.author_id
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.post, notice: 'Comment was successfully posted.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment.post, notice: 'Comment was successfully edited.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    postid = @comment.post_id
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to post_url(postid) }
      format.json { head :no_content }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for @comment  do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.hidden_field :post_id, :value => @comment.post_id %>
  </div>

  <div class="control-group">
    <%= f.label  :author %> (<%= link_to 'Create New', new_author_path %>)
    <%= f.collection_select :author_id, Author.all.sort_by {|i| i.name.downcase}, :id, :name, {include_blank: 'select an Author'} %>
  </div>

  <div class="control-group">
    <%# f.label :content %><br />
    <%= f.text_area :content, {cols: 80, rows: 12} %>
  </div>

  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

Post: <%= @comment.post.title %><br>
by <%= @comment.author.name %><br> <br>

<%= render 'form' %>

<%= link_to 'Back', post_path(@comment.post_id) %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.content %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @comment.content %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>