config/routes.rb
RailsBlog::Application.routes.draw do
  resources :authors

  resources :posts do
    resources :comments, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :comments

  root :to => 'posts#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :posts
  has_many :comments, :through => :posts
  attr_accessible :name, :username

  validates :name, :username, :presence => true 
  validates_uniqueness_of :username, :case_sensitive => false
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @authors }
    end
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @author = Author.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/new
  # GET /authors/new.json
  def new
    @author = Author.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/1/edit
  def edit
    @author = Author.find(params[:id])
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(params[:author])

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render json: @author, status: :created, location: @author }
      else
        format.html { render action: "new" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /authors/1
  # PUT /authors/1.json
  def update
    @author = Author.find(params[:id])

    respond_to do |format|
      if @author.update_attributes(params[:author])
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="control-group">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Listing authors</h1>

<table>
  <tr>
    <th>Name</th>
    <th>User Name</th>
    <th># Posts</th>
    <th># Comments</th>
    <th></th>
    <th></th>
  </tr>

<% @authors.each do |author| %>
  <tr>
    <td><%= link_to author.name, author %></td>
    <td><%= link_to author.username, author %></td>
    <td><%= author.posts.size %></td>
    <td><%= author.comments.size %></td>
    <td><%= link_to 'Edit', edit_author_path(author) %></td>
    <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @author.name %>
</p>
<p>
  <b>User Name:</b>
  <%= @author.username %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>
<br><br>

<h2>All Posts</h2>
<table>
<% @author.posts.each_with_index do |post, index| %>
  <tr>
    <td valign="top"><h3><%= link_to index+1, post %></h3></td>
    <td colspan="100%"><%= post.preview.html_safe %></td>
  <tr>
  <tr>
    <td></td>
    <td> 
      <%= link_to 'Edit Post', edit_post_path(post) %>
    | <%= link_to 'Delete Post', post, method: :delete, data: { confirm: 'Are you sure?' } %>
    </td>
  </tr>
<% end %>
</table>


<h2>All Comments</h2>
<table>
<% @author.comments.each_with_index do |comment, index| %>
  <tr>
    <td valign="top"><h3><%= link_to index+1, comment %></h3></td>
    <td colspan="100%"><%= comment.preview.html_safe %></td>
  <tr>
  <tr>
    <td></td>
    <td>
      <%= link_to 'Edit Comment', edit_post_comment_path(comment.post, comment) %>
    | <%= link_to 'Delete Comment', comment, method: :delete, data: { confirm: 'Are you sure?' } %>
    </td>
  </tr>
<% end %>
</table>

<br><br>