config/routes.rb
RailsBlog::Application.routes.draw do
  resources :authors

  resources :posts do
    resources :comments, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :comments

  root :to => 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author
  has_many   :comments
  attr_accessible :content, :title, :author_id

  validates :content, :title, :author_id, :presence => true 

  include ActionView::Helpers::UrlHelper
  # include  ActionDispatch::Http::Url

  PREVIEW_LIMIT = 800
  LINE_LIMIT = 12

  SHORTEN_LIMIT = 10000

  def paragraphize
    body = content.split("\n").collect{|paragraph| "<p>#{paragraph}</p>"}.join("\n")
    body
  end

  def preview
    if content.scan("\n").size > LINE_LIMIT
      paragraphize[0..PREVIEW_LIMIT].split("\n")[0..LINE_LIMIT].collect{|paragraph| "<p>#{paragraph}</p>"}.join("\n") + ellipsis
    elsif paragraphize.size > PREVIEW_LIMIT
      paragraphize[0..PREVIEW_LIMIT] + ellipsis
    else
      paragraphize
    end
  end

  def shorten
    if paragraphize.size > SHORTEN_LIMIT
      paragraphize[0..SHORTEN_LIMIT] + ellipsis
    else
      paragraphize
    end
  end

  def ellipsis
    "<strong>#{link_to '...', '/posts/'+self.id.to_s}<strong>"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    if request.referer.is_a? String
      resource_type = request.referer.split("/")[-2]
      resource_id   = request.referer.split("/")[-1]
      @selected_author  = resource_id.to_i  if resource_type = "authors"
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])

    @selected_author  = @post.author_id
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label  :author %> (<%= link_to 'Create New', new_author_path %>)
    <%= f.collection_select :author_id, Author.all.sort_by {|i| i.name.downcase}, :id, :name, {include_blank: 'select an Author', selected: @selected_author} %>
  </div>

  <div class="control-group">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <div class="control-group">
    <%= f.label :content %><br />
    <%= f.text_area :content, {cols: 80, rows: 100} %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Author</th>
    <th>Title</th>
    <!-- <th>Content</th> -->
    <th># Comments</th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= link_to post.author.name, author_path(post.author_id) %></td>
    <td><%= link_to post.title, post %></td>
    <!-- <td><%# link_to post.content, post %></td> -->
    <td><%= post.comments.size %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <b>Author:</b>
  <%= link_to @post.author.name, author_path(@post.author_id) %>
</p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Posted at:</b>
  <%= @post.created_at %>
</p>

<p>
  <%= @post.paragraphize.html_safe %>
</p>

<br><br>

<table>
<% @post.comments.each do |comment| %>
  <tr>
    <td colspan="100%"><%= comment.paragraphize.html_safe %></td>
  <tr>
  <tr>
    <td>
     &nbsp; - <%= comment.author.name %> 
    </td>
  </tr>
  <tr>
    <td>
    <%= comment.created_at %>
    | <%= link_to 'Edit Comment', edit_post_comment_path(@post, comment) %>
    | <%= link_to 'Delete Comment', comment, method: :delete, data: { confirm: 'Are you sure?' } %>
    </td>
  </tr>
  <tr><td>&nbsp;</td></tr>
<% end %>
</table>

<br><br>
<%= link_to 'Post New Comment', new_post_comment_path(@post.id) %>
<%# render :partial => "posts/form", :locals => {:comment => Comment.new} %>

<br><br><br><br>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>